name: Check Tickets
on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟检查一次
  workflow_dispatch:      # 允许你手动点击按钮测试

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Melon Ticket
        uses: mooyoul/melon-ticket-actions@v1.1.5  # 使用最新版本
        with:
          product-id: '212567'    # 演出ID
          schedule-id: '100001'   # 场次ID
          seat-id: '1_0'               # 通常 1_0 代表检查所有座位，或者特定区域ID
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
